### ISSUE TITLE
При компиляции jar файла

### ISSUE THREAD

**Issue by yanislavb** [jphp-compiler/develnext#8]
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/scene/input/KeyCombination
        at org.develnext.jphp.ext.javafx.bind.KeyCombinationMemoryOperation.getOperationClasses(KeyCombinationMemoryOperation.java:13)
        at php.runtime.memory.support.MemoryOperation.register(MemoryOperation.java:235)
        at php.runtime.ext.support.Extension.registerMemoryOperation(Extension.java:102)
        at org.develnext.jphp.ext.javafx.JavaFXExtension.onRegister(JavaFXExtension.java:75)
        at php.runtime.env.CompileScope.registerExtension(CompileScope.java:332)
        at php.runtime.env.CompileScope.registerExtension(CompileScope.java:292)
        at php.runtime.env.CompileScope.registerExtension(CompileScope.java:284)
        at php.runtime.launcher.Launcher.initExtensions(Launcher.java:219)
        at php.runtime.launcher.Launcher.run(Launcher.java:247)
        at php.runtime.launcher.Launcher.run(Launcher.java:241)
        at php.runtime.launcher.Launcher.run(Launcher.java:237)
        at php.runtime.launcher.Launcher.main(Launcher.java:328)
Caused by: java.lang.ClassNotFoundException: javafx.scene.input.KeyCombination
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 12 more

**Comment by dim-s** [comment]
Нужно собирать с помощью Oracle JDK 8, а не ниже версией.
